### ISSUE TITLE
The file can download but can't be open. Display file format error

### ISSUE THREAD

**Issue by luffyZh** [mgcrea/node-xlsx#107]
In my project , the browser can download the 'xx.xlsx' file, but the file can't be open.
Even the simplest code to build the file.
```
 const filename = `xxxx_${startDate}_${endDate}.xlsx`;
  // eslint-disable-next-line
  const buffer = excel.build([{ name: 'sheet1', data: [['date', 'showNum']].concat([]) }]);
...
 res.status(200).attachment(filename).send(buffer);
```
Open the file, it will show the file format is wrong.

```
os: Mac
node: v8.14.0
```

**Comment by luffyZh** [comment]
```
// The same code
const buffer = xlsx.build([{ name: 'sheet1', data: [['date', 'showNum']].concat([]) }]);
res.status(200).attachment('def.xlsx').send(buffer);
```
Another project  is right:
<img width="648" alt="default" src="https://user-images.githubusercontent.com/17840558/50943498-ac1add80-14c7-11e9-8a04-340e02365794.png">

<img width="645" alt="default" src="https://user-images.githubusercontent.com/17840558/50943431-6a8a3280-14c7-11e9-8cc7-4b5cbf14f515.png">

But the new project is wrong:(the new project only upgrade some packages)
<img width="648" alt="default" src="https://user-images.githubusercontent.com/17840558/50943541-da98b880-14c7-11e9-8ba6-994d19c652a6.png">
<img width="645" alt="default" src="https://user-images.githubusercontent.com/17840558/50943551-e5ebe400-14c7-11e9-9c53-0ef4c52bdcc2.png">

**Comment by luffyZh** [comment]
The project start with [React-Starter-Kit](https://github.com/kriasoft/react-starter-kit), and it's not work with it.

**Comment by luffyZh** [comment]
sorry, it seems not the 'node-xlsx' problem, it's belong to the react-starter-kit.

**Comment by TCMiranda** [comment]
@luffyZh Can you tell me what the problem was? I am also getting this exactly output
Thanks

**Comment by luffyZh** [comment]
@TCMiranda The solution is here ======> [solution](https://github.com/kriasoft/react-starter-kit/issues/1701)
