### ISSUE TITLE
req.files.file

### ISSUE THREAD

**Issue by sun-zy** [mgcrea/node-xlsx#117]
问一下，`${__dirname}/myFile.xlsx`  这个是如何指定的

**Comment by Jonham** [comment]
let me translate Chinese above.

hi，how is `${__dirname}/myFile.xlsx` been pointed to ?

**Comment by Jonham** [comment]
@sun-zy 
this is a Node.js `fs` module question.

`__dirname` means current file's directory.
`myFile.xlsx` is a DEMO file, you can change for any file name you want.

------ in Chinese 
你问的是个 Node.js 问题，查看 Node.js的fs，文件读取模块的文档。
__dirname是当前js代码文件所在的目录，dir就是目录 directory的缩写。
\`${__dirname}/myFile.xlsx\`是用了ES6的 模板文本插入方式。
__dirname在这里会被当成变量替换掉。效果类似于： __dirname + '/myFile.xlsx'。

你可以随意改成，你本地需要测试的Excel文件的路径。比方说，跟你的JS代码在一起的A.xlsx文件，可以直接写成 \`${__dirname}/A.xlsx\`。注意两个反引号(在键盘上，1的左边)

**Comment by sun-zy** [comment]
Got it, thank you
