### ISSUE TITLE
excel parser number bug 

### ISSUE THREAD

**Issue by ipengyo** [mgcrea/node-xlsx#123]
A positive integer in excel becomes a decimal after export

![image](https://user-images.githubusercontent.com/9323722/61786520-72486d80-ae40-11e9-8467-5bfb51539629.png)

![image](https://user-images.githubusercontent.com/9323722/61786465-5218ae80-ae40-11e9-9d7e-edc6f4f5b457.png)

**Comment by mgcrea** [comment]
Unfortunately the bug appears to be upstream in [js-xlsx](https://github.com/SheetJS/js-xlsx) that is used for parsing.

As a workaround you can use `parseXSLX(file, {raw: false}))` to get strings where the bug does not occur.

**Comment by prashantnagawade** [comment]
> Unfortunately the bug appears to be upstream in [js-xlsx](https://github.com/SheetJS/js-xlsx) that is used for parsing.
> 
> As a workaround you can use `parseXSLX(file, {raw: false}))` to get strings where the bug does not occur.

@mgcrea can you please tell more about the `{raw: false}` option used here, what exactly does it solve and which type of fields/datatypes will be affected due to this option?
