### ISSUE TITLE
help ! data in xlsx is int but result is float

### ISSUE THREAD

**Issue by Upwitheva** [mgcrea/node-xlsx#124]
I've checked the data in the original workbook.    Original data is 6440000 but parse to 6439999.999999999

**Comment by ipengyo** [comment]
Yes, I also encountered the same problem. #123

**Comment by Upwitheva** [comment]
@mgcrea  :(

**Comment by mgcrea** [comment]
Could any of you share a basic workbook reproducing the issue so that I can take a look?

**Comment by Upwitheva** [comment]
[buildRestaurant.xlsx](https://github.com/mgcrea/node-xlsx/files/3429357/buildRestaurant.xlsx)

**Comment by mgcrea** [comment]
Can't reproduce: https://gist.github.com/mgcrea/f4c2a00643dbcc1f065574c6881a7f58

**Comment by mgcrea** [comment]
Unfortunately the bug appears to be upstream in [js-xlsx](https://github.com/SheetJS/js-xlsx) that is used for parsing.

As a workaround you can use `parseXSLX(file, {raw: false}))` to get strings where the bug does not occur.

**Comment by Upwitheva** [comment]
It worked!!! Thx for your reply!!
