### ISSUE TITLE
The generated buffer is too large

### ISSUE THREAD

**Issue by ALLTAKENS** [mgcrea/node-xlsx#128]
`const buffer = xlsx.build([{ name: 'topics', data: answers }, { name: 'respondents', data: repondents }])`
 `fs.writeFileSync('data.xlsx', buffer, { 'flag': 'w' })`
The buffer and resulting file size is 10468kb，it's too big!!after i open the file and save it, the size is now 1417kb, that is the normal size.
How do I generate a normal size buffer

**Comment by goldalworming** [comment]
it should not be closed. the bug still exist
