### ISSUE TITLE
How to build base on a xlsx file?

### ISSUE THREAD

**Issue by klibing** [mgcrea/node-xlsx#129]
How to build base on a xlsx file?

**Comment by Wil-g2** [comment]
Use this example for build base on a xlsx file:
<code>const file = xlsx.parse('./test.xlsx'); // read file xlsx 

console.log(file);   // print context xlsx in console 

var buffer = xlsx.build(file, options); // Returns a buffer

fs.writeFile('test1.xlsx', buffer, function (err) { //save xlsx in disk 

    if (err) throw err;

    console.log('File is created successfully.');
  });  

/** remember import fs for save file in disk */  
</code>
