### ISSUE TITLE
How to set some cell to bold font?

### ISSUE THREAD

**Issue by xeoshow** [mgcrea/node-xlsx#133]
Hello,

I am trying to use node-xlsx to generate excel file, while a little confused how to set some cell to bold font, and did not find document related, could any one could please kindly help?

Thanks!

**Comment by saselezn** [comment]
Hi, I think it is not possible. Node-xlsx based on sheetjs library. Sheetjs allows to add styles to cell in pro version only. [#965](https://github.com/SheetJS/sheetjs/issues/965)

**Comment by Rajon9** [comment]
哪里可以联系到您老哥，有点问题想请教一下 可以微信 联系下吗？
我的邮箱 rajonhtc@gmail.com 感激不尽。

**Comment by Rajon9** [comment]
Where can I contact your brother? If you have any questions, can you contact me via wechat?

My email address is rajonhtc@gmail.com. Thank you very much.

@xeoshow
