### ISSUE TITLE
Please publish new version to npm - ReDoS fix

### ISSUE THREAD

**Issue by marko-jankovic** [mgcrea/node-xlsx#144]
Hi!

Latest version 0.15 is using xlsx version 0.14.1 that is vulnerable to ReDoS attacks. https://snyk.io/vuln/SNYK-JS-XLSX-585898

I see you already have fix on master. Could you please publish to npm?

Thank you!

**Comment by mgcrea** [comment]
Done! `v0.16.0`

**Comment by marko-jankovic** [comment]
v0.16 requires babel

Cannot find module '@babel/runtime/helpers/interopRequireDefault'

**Comment by marko-jankovic** [comment]
thank you for quick fix 💪
