### ISSUE TITLE
Parse a remote file

### ISSUE THREAD

**Issue by federicovezzoli** [mgcrea/node-xlsx#153]
Sorry, very new to node, I'm trying to parse a remote file coming from our cms, but I always get:

`xlsx.parse('https://cdn.sanity.io/files/....'));`
`Error: ENOENT: no such file or directory, open 'https://cdn.sanity.io/files/....'`

I really don't understand how to handle this.
The file is correctly reachable and if I use the same file locally it just works:

`const workSheetsFromFile = xlsx.parse(`${__dirname}/certs.xlsx`);`

What am I missing?

**Comment by federicovezzoli** [comment]
Not sure if anyone interested, but using got I finally reached the file and it's content, unlucky I still don't understand how to pass it down to xlsx.parse, following the doc just don't work.

` const responsePromise = got('https://....');
  const [response] = await Promise.all([responsePromise]);
  const buffer = Buffer.from(response.body);

  fs.writeFileSync(`${__dirname}/file.xlsx`, buffer);

  const workSheetsFromFile = xlsx.parse(
    `${__dirname}/file.xlsx`
  );`
  
  I always get: _Error: End of data reached (data length = 102379, asked index = 150950). Corrupted zip ?_

**Comment by iosyyy** [comment]
I am not a developer of this framework, but I can answer your question. Your file can only be encoded and decoded through his tool, which is parse and build.

**Comment by iosyyy** [comment]
Anyway, I don't think this tool is very perfect. There are many vulnerabilities in many places. It is recommended to use native js-xlsx
