### ISSUE TITLE
Can't set row height

### ISSUE THREAD

**Issue by JohnnyYeen** [mgcrea/node-xlsx#154]
Hello, 
I was trying to set row height, and I found it does not work ( It did work on column width, and I was very confused ). 
Here is the some of the code in my project ( followed samples ): 

 **const options = { '!merges': ranges, '!cols': columns, '!rows': rows };
 const buffer = xlsx.build([{name: "genxlsx", data: this.getSheetData()}], options);**

'rows' array with formed data was like this: 
**[{ hpx: 200}, {...}, ...]** 
I wonder if I did something wrong? How can I make this work？
Thanks！

**Comment by Morris-Mao** [comment]
The same issue!!!!

**Comment by dongjuny** [comment]
Me too
