### ISSUE TITLE
How to apply Formatting/Style in new version ?

### ISSUE THREAD

**Issue by ashu-daffodil** [mgcrea/node-xlsx#16]
Till version 0.4 input was given like :

[{"value":"Name","bold":true,"formatCode":"General","autoWidth":true},"value":"Age","bold":true,"formatCode":"General","autoWidth":true}]

So it was easy to format. But since v0.5 , it takes data in Array of Array form like :

[["Name","age"],["Ashu","25"]

Can't figure out how to apply style in this new format.

**Comment by sgaestel** [comment]
I'm also interested by the way to apply formatting in 0.5 version. Is it still possible ?

**Comment by M4GNV5** [comment]
still no solution for this?

**Comment by Youmoo** [comment]
Also interested.

**Comment by Zalberth** [comment]
the package exceljs may be a help

**Comment by mattkosoy** [comment]
+1 also interested

**Comment by mgcrea** [comment]
Since 7979d1799178f4e2f08fd8d15a37be3d8d3a7815 landed, you can pass raw descriptors that sould enable you to apply any formatting you need. Tell me if that fixes it for you.

**Comment by makenai** [comment]
I can sort of see how this is done, by passing an object like this as the value of a cell:

`{ v: 'SomeValue', s: '...' }`

However, I'm not sure what's supposed to go into the 's' field to represent the styling information.

**Comment by jeerbl** [comment]
Anyone figured a way to do that?

**Comment by jeerbl** [comment]
Hi @mgcrea!
It would be nice having this in the documentation if possible. @makenai di you find a way?

Thanks
Jerome

**Comment by natikos** [comment]
hey, any updates here?
