### ISSUE TITLE
Buffer is no defined error

### ISSUE THREAD

**Issue by jbwl** [mgcrea/node-xlsx#161]
When using this in the browser via VueJS, trying to build an xlsx throws "Buffer is not defined" at this line
index.js:79

`return excelData instanceof Buffer ? excelData : (0, _bufferFrom.default)(excelData, 'binary');`

I added node-xlsx via yarn add. I also tried to add explicitely the buffer-from package, but that didn't solve the problem.

**Comment by mgcrea** [comment]
This is a pure nodejs package, just use sheetjs directly for browser usage.
