### ISSUE TITLE
Parse can't fill the blank cells

### ISSUE THREAD

**Issue by zxq08** [mgcrea/node-xlsx#165]
if my Excel has blank cells, they will be ignored, which may cause dislocation。

**Comment by LucasDelboni** [comment]
I was with the same problem. I figured out that if you send the parameter `{sheetStubs:true}` to the XLSX's method `readFile` it read empty cells as `null`. And you can pass parameter to the XLSX's method `readFile`.

So, if you want to continue using node-xlsx, you can just call this way:
`nodeXlsx.parse('filename', {sheetStubs:true});`
