### ISSUE TITLE
 TypeError: input.replace is not a function

### ISSUE THREAD

**Issue by colo13verdadeo** [mgcrea/node-xlsx#174]
input = input.replace(/[^\w\+\/\=]/g, "");
                                      ^
```TypeError: input.replace is not a function```

Code:
```const xlsx = require( 'node-xlsx');
const fs = require('fs')

//Cierra dependencias


function importar(ruta){
    archivo = XLSX.readFile(ruta) 
    hojas = archivo.SheetNames;
    console.log(hojas)
    datos = XLSX.utils.sheet_to_json(archivo.Sheets[hojas[0]])
    console.log(datos)
    console.log()
    for(itemfila of datos){
    console.log(datos['Usuarios'])}
}


console.log(xlsx.parse(`./importarexcel.xlsx`))```

**Comment by binajmen** [comment]
Hello @colo13verdadeo, I have the same issue (https://github.com/mgcrea/node-xlsx/issues/182). Did you find a solution?

**Comment by brayanL** [comment]
I'm still getting this error, any solution?

**Comment by colo13verdadeo** [comment]
No @binajmen :c

**Comment by Jmennius** [comment]
Had the same issue when working with a data buffer provided by `cypress`. In my case the buffer was actually an `ArrayBuffer` (as provided by cypress).
So to make it work with xlxs I had to convert it to a regular `Buffer`: `Buffer.from(array_buffer)`.
