### ISSUE TITLE
Error: Unsupported ZIP file

### ISSUE THREAD

**Issue by feelthemoon** [mgcrea/node-xlsx#176]
Error: Unsupported ZIP file
main        |     at parse_zip (/app/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:21569:9)
main        |     at read_zip (/app/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:21917:9)
main        |     at readSync (/app/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:21986:69)
main        |     at Object.readFileSync (/app/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:22009:9)
main        |     at Object.parse (/app/node_modules/node-xlsx/lib/index.js:23:85)
main        |     at TableService.setTableData (/app/dist/tables/table.service.js:93:46)
main        |     at TableController.setTableData (/app/dist/tables/table.controller.js:40:37)
main        |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
main        |     at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
main        |     at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17

**Comment by feelthemoon** [comment]
Solved

**Comment by redvelvet-fan** [comment]
> Solved

how did you solved?

**Comment by feelthemoon** [comment]
> > Solved
> 
> 
> 
> how did you solved?

I used the wrong method. Append instead write, where append was at wrong place. It's not a library trouble I guess.
