### ISSUE TITLE
When parsing a date, it returns the excel-date format

### ISSUE THREAD

**Issue by jeer00** [mgcrea/node-xlsx#180]
When parsing a date, it seems to return the excel-date-format. Although the .xlsx hasnt specified that date-format. Example: 
'18/03/2017' becomes: 42812

**Comment by jahon** [comment]
please setting the options;

`const options = {
  type: "buffer",
  cellDates: true,
  cellHTML: false,
  dateNF: "yyyy-mm-dd hh:mm:ss",
  cellNF: true
};

// Parse a file
const workSheetsFromFile = xlsx.parse(fileName, options);`
