### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by KatsuragiCSL** [mgcrea/node-xlsx#184]
This file can be opened with libreoffice calc, but it causes crash when handled by node-xlsx with xlsx.parse() as buffer.
[crash2.zip](https://github.com/mgcrea/node-xlsx/files/9400085/crash2.zip)

**Comment by reviewher** [comment]
LibreOffice Calc shows an error.  Excel 2019 shows an error.  Can you download the zip file and open it?

**Comment by KatsuragiCSL** [comment]
![Screenshot from 2022-08-23 15-31-12](https://user-images.githubusercontent.com/44156690/186098576-bd131121-8472-4389-91f6-997a95c34113.png)

It gives me this in LibreOffice Calc (in Ubuntu 20.04)

**Comment by reviewher** [comment]
That looks like LibreOffice Calc tried to save the file.  Excel crashes :(

<img width="241" alt="node-xlsx-184" src="https://user-images.githubusercontent.com/24845478/186100482-6bb57e4a-781a-4a9f-b140-b9df48069cc3.png">
