### ISSUE TITLE
Update xlsx package because vulnerabilities

### ISSUE THREAD

**Issue by jonathan-4iTester** [mgcrea/node-xlsx#189]
Hello,

Could you please update the xlsx dependency lib because the npm audit is reporting this issue:

                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution in sheetJS                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ xlsx                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.19.3                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ node-xlsx                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ node-xlsx > xlsx                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-4r6h-8v6p-xvw6            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 moderate severity vulnerability in 1044 scanned packages
  1 vulnerability requires manual review. See the full report for details.

Best Regards.

**Comment by jonathan-4iTester** [comment]
@mgcrea , any news?

**Comment by joyce-4i** [comment]
I also have this problem. I was trying search a solution but i don't find. The community needs a solution for this problem.  
![image](https://user-images.githubusercontent.com/97473854/235940013-2ed86c16-979e-4740-8e7c-1cdf2db7a155.png)

**Comment by Cellule** [comment]
See https://github.com/SheetJS/sheetjs/issues/2822 for discussion/information about how to update

**Comment by dafanzhi** [comment]
I followed the https://github.com/SheetJS/sheetjs/issues/2822 and reinstalled the xlsx, but still got the same vulnerability tips:
<img width="1068" alt="image" src="https://github.com/mgcrea/node-xlsx/assets/53632540/c5f64e5d-8586-486c-b49c-14dc932326fa">
What should i do? 
I don't know what's the relationships between the node-xlsx and xlsx, can you help to provide detailed instructions?
Thanks a lot!

**Comment by WilhelmStein** [comment]
Interested in how to fix this as well. Simply updating from the cdn does not seem to work for me :(
Could anyone better illustrate the steps we must take to solve this issue :) ?

**Comment by WilhelmStein** [comment]
> See [SheetJS/sheetjs#2822](https://github.com/SheetJS/sheetjs/issues/2822) for discussion/information about how to update

Interested in how to fix this as well. Simply updating from the cdn does not seem to work for me :(

**Comment by milpalabras** [comment]
until @mgcrea fix this vulnerabilities,  you can override in packaje.json to use the last xlxs module without vulnerabilities (need remove node-xlsx and reinstall again with the override version in packaje,json)
see: https://docs.sheetjs.com/docs/getting-started/installation/nodejs/

**Comment by dafanzhi** [comment]
@milpalabras, i specified the overrides in the package.json:
<img width="906" alt="image" src="https://github.com/mgcrea/node-xlsx/assets/53632540/6e5c2388-d50a-4a3a-8a85-06213476ef1a">

then removed the xlsx and node-xlsx, and resintall them:
<img width="781" alt="image" src="https://github.com/mgcrea/node-xlsx/assets/53632540/46355631-bf7d-4bdc-bea8-b3265b75786a">

Still got the same result.
Can you help to provide detailed instructions to install  node-xlsx and eliminate the vulnerabilities  error tips?

**Comment by WilhelmStein** [comment]
I made a fork and updated the dependency, but then two tests broke. In inspecting them, I noticed that the [tests](https://github.com/mgcrea/node-xlsx/blob/master/test/specs/build.spec.ts#L10-L25) were only checking the first 10 bytes of the files, which I found a bit odd.

In any case, there seems to be a discrepancy between the 5th byte of the [fixture files](https://github.com/mgcrea/node-xlsx/tree/master/test/fixtures) and the output from the `xlsx` package. I took a look with a hex editor, and the first 4 bytes seem to conform to the `.xlsx` file format. I am having some trouble understanding what that change signifies in the 5th byte.

**Comment by WilhelmStein** [comment]
Cheers! Btw, what was the issue with the tests after updating to the latest dep version of xlsx? From: Olivier LouvignesSent: Thursday, 25 May 2023 15.07To: mgcrea/node-xlsxCc: Baron Wilhelm Stein; CommentSubject: Re: [mgcrea/node-xlsx] Update xlsx package because vulnerabilities (Issue #189) Just published the v0.22.0 release with updated deps, should fix your issues.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by dafanzhi** [comment]
The issue still exists in v0.22.0:

➜  bodhi git:(3.5.11) ✗ npm rm node-xlsx
removed 10 packages and audited 210 packages in 2.095s

14 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │      New major version of npm available! 6.14.12 → 9.6.7      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v9.6.7   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

➜  bodhi git:(3.5.11) ✗ npm rm xlsx
removed 5 packages and audited 209 packages in 1.931s

14 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
➜  bodhi git:(3.5.11) ✗ npm install node-xlsx@0.22.0
+ node-xlsx@0.22.0
added 7 packages from 2 contributors, removed 1 package, updated 3 packages and audited 219 packages in 2.968s

14 packages are looking for funding
  run `npm fund` for details

**found 2 vulnerabilities (1 moderate, 1 high)**
  **run `npm audit fix` to fix them, or `npm audit` for details**
