### ISSUE TITLE
Utilize web workers

### ISSUE THREAD

**Issue by sochka** [mgcrea/node-xlsx#21]
Hi, 
What do you think about paralleling this lib somehow? Working with xls seems to mostly CPU-bound and therefore not very good to deal with in event loop thread.

https://github.com/SheetJS/js-xlsx this lib, used by this project supports web workers. On the other hand there is an implementation of web workers for node.js - https://www.npmjs.com/package/webworker-threads . 

Thanks for your work!

**Comment by mdsaleemj** [comment]
Does the module parse the xlsx file synchronously ? 
 If parsing logic happens synchronously, then it will block the main event loop thread. one has to make it run asynchronously.
