### ISSUE TITLE
Issue with same data record in subsequent row

### ISSUE THREAD

**Issue by Jawad-LiftOff** [mgcrea/node-xlsx#22]
If I have the same data on the subsequent row it gets ignored and I end up in a cell lesser than what actually is. For Example if I have the data like in below grid it just returns me [[a,b,c,d]] instead of [[a,b,c,c,e]]

![image](https://cloud.githubusercontent.com/assets/12030499/8633324/072357b2-27e0-11e5-8921-37192ab755ef.png)

**Comment by mgcrea** [comment]
Please provide a reproducible test-case and I'll have a look.
