### ISSUE TITLE
what a pite, can't set the width of colum!

### ISSUE THREAD

**Issue by ideayuye** [mgcrea/node-xlsx#25]
I want set the width of each columns.Then i view the source code,but I didn't find the api.

**Comment by dr-dimitru** [comment]
+1

**Comment by ozkxr** [comment]
+1

**Comment by GreenPioneer** [comment]
+1

**Comment by GreenPioneer** [comment]
ws['!cols'] - https://www.npmjs.com/package/xlsx. if someone is interested in submitting a pr

**Comment by danedavid** [comment]
What if we won't different column width arrays for each worksheet?

**Comment by Octobug** [comment]
> What if we won't different column width arrays for each worksheet?

Just put `options` in each sheet data:

```js
var buffer = xlsx.build([
  {name: 'myFirstSheet', data: dataSheet1},
  {name: 'mySecondSheet', data: dataSheet2, options: sheetOptions},
]); // Returns a buffer
```

Note that this feature might not work for old versions. I'm not sure of which version brought this feature.
