### ISSUE TITLE
Error on a list or range that contains merged cells. 

### ISSUE THREAD

**Issue by oopyoung** [mgcrea/node-xlsx#32]
Hello,
I find a question when I read the xlsx contains merged cells
![xlsx](https://cloud.githubusercontent.com/assets/11434784/14074074/e1568e70-f500-11e5-8db9-7ab327957a7c.png)
![result](https://cloud.githubusercontent.com/assets/11434784/14074126/47ccd06a-f501-11e5-9449-1ce30663d09c.png)

Sorry to include Chinese, but I hope you can help me to solve this problem, thank you very much!!!

**Comment by mgcrea** [comment]
That's, normal behavior, as far as I know.

You can implement some basic post processing logic to fill the gaps.
