### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by zhaoxingyue** [mgcrea/node-xlsx#37]
I use it to exports excel but got an error ,I need you help ,thanks you very much.

var excelData = _xlsx2.default.write(workBook, Object.assign({}, defaults, o
                                                        ^
TypeError: undefined is not a function

**Comment by Hunter-Dolan** [comment]
I was just experiencing the same problem. It appears this lib is expecting everyone to be on ES6 by now. 

I was able to resolve this issue by adding the following package:
https://www.npmjs.com/package/object-assign

And then including the following at the start of my main package file:
```Object.prototype.assign = require("object-assign")```

Hope this helps.
