### ISSUE TITLE
How to span columns?

### ISSUE THREAD

**Issue by WittCsharp** [mgcrea/node-xlsx#41]
May you help me? I don't know how to span columns or rows

**Comment by pineapplebin** [comment]
for 0.7.4
``` node
// merge A1:D1
xlsx.build(worksheets, { '!merges': [ { s: {c: 0, r: 0}, e: {c:3, r: 0} } ] })
```
you can read more about it in [js-xlsx](https://github.com/SheetJS/js-xlsx)

**Comment by mgcrea** [comment]
Documented here: 9e529d26fa402bd265b13f9bb51541cb86f6bc48
