### ISSUE TITLE
Bug in workbook sheet writer - Date convertion

### ISSUE THREAD

**Issue by riceian** [mgcrea/node-xlsx#44]
in helpers.js the buildExcelDate function returns the wrong date in the case that !is1904
It should read:
const buildExcelDate = (value, is1904) => {
  if(is1904) value+=1462;
 const epoch = Date.parse(value);
return (epoch - originDate) / (24 \* 60 \* 60 \* 1000)
};

**Comment by lohithram** [comment]
This is still a valid problem in IE11
