### ISSUE TITLE
Cannot find module 'jszip

### ISSUE THREAD

**Issue by Sasy91** [mgcrea/node-xlsx#46]
I try to use this package by npm install node-xlsx and the i import the package
 import xlsx from 'node-xlsx'; 

but when i run the app it gives 

Uncaught Error: Cannot find module 'jszip'   install.js:78

then i install jszip by 
import xlsx from 'jszip'; 
but it gives the same error

**Comment by N00D13** [comment]
Same but different.

# Missing jszip in browserify bundle
The require call for jszip uses a concatenated string require('js'+'zip') which stops browserify from including it. The results in a runtime error Cannot find module 'jszip'.

**Comment by gruentee** [comment]
@N00D13 Are you talking about the file in the `dist` folder? I thought this already is the bundled version?

**Comment by thearabbit** [comment]
I have the same problem, how to fix?
