### ISSUE TITLE
Javascript heap out of memory (Node)

### ISSUE THREAD

**Issue by wshager** [mgcrea/node-xlsx#47]
Javascript heap out of memory when trying to build a XLSX for a modest set of 133 rows of 3 columns in Node. The error is caused by buildSheetFromMatrix.

**Comment by jude-liu** [comment]
@wshager I met the same problem when build a XLSX with "**xlsx.build([{name: "mySheetName", data: sheetData}])**" function, finnaly i found the reason is that every element in array **sheetData**  is an Object not a array, when i change to array the problem is resovled.

**Comment by wshager** [comment]
In that case wouldn't it be better to check for type? And either throw a predictable error or transform on the fly?

**Comment by jude-liu** [comment]
@wshager  For now, i just iterate through the array "**sheetData**" to convert the object into an array.

**Comment by dotob** [comment]
i have the same poblem but with array of array for data. but with a more data (~30k rows). 

logs:
==== JS stack trace =========================================

Security context: 0x26a78695 <JS Object>
    1: encode_cell [/home/termopt10/autotest/lps/tools/node_modules/xlsx/xlsx.js:~11451] [pc=0xf1888c9d] (this=0x2b898889 <an Object with map 0x2fc58e09>,cell=0x362a5fc1 <an Object with map 0x2fc6a815>)
    2: buildSheetFromMatrix(aka buildSheetFromMatrix) [/home/termopt10/autotest/lps/tools/node_modules/node-xlsx/lib/helpers.js:~31] [pc=0xf18877b9] (this=0x26a080c9 <undefined>,data=0x263c2781 <JS ...
