### ISSUE TITLE
Cannot resolve module 'fs' 

### ISSUE THREAD

**Issue by gongph** [mgcrea/node-xlsx#52]
```
build.js:667 ./~/xlsx/xlsx.js
Module not found: Error: Cannot resolve module 'fs' in D:\workSpace\git\vue-xlsx\node_modules\xlsx
```

**Comment by gongph** [comment]
@mgcrea  help

**Comment by vineetkumar1511** [comment]
Any update on this ?

**Comment by mgcrea** [comment]
`fs` is part of NodeJS core, try to update your NodeJS version.

**Comment by Roman86** [comment]
hi @mgcrea ! People like me may want to use it completely client-side (which can't import "fs" and any other node tool). Version `0.23.0` works great in web browser. But not `0.24.0` unfortunately. Maybe you can advise something to make it work again? Maybe some client-side bundle export possible?

**Comment by gongph** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
