### ISSUE TITLE
Reading file ignores empty rows at top of sheet

### ISSUE THREAD

**Issue by geon** [mgcrea/node-xlsx#53]
I have a file with an empty row at the top. It gets ignored, so that the index of the `.data` property doesn't match the work sheet.

**Comment by timrobinson33** [comment]
did anyone find a solution to this? I notice that blank columns on the left are also ignored. I have tried `sheetStubs` and `blankrows` but neither seems to make any difference

**Comment by Prinzhorn** [comment]
This worked for me, by forcing the range to always start at A1:

```js
const sheets = xlsx.parse(buffer, {
  range: (sheet) => {
    // Make sure the range always starts at A1 and doesn't skip empty rows/columns.
    const range = sheet['!ref'];
    const [, to] = range.split(':');
    return ['A1', to].join(':');
  }
});
```
