### ISSUE TITLE
Can not parse the excel date to javascript date type

### ISSUE THREAD

**Issue by RickonChen** [mgcrea/node-xlsx#56]
Hey, guys, here is a problem I got: There is a column in my xlsx file that is to describe time. And if I input a '#08:30', then it can parse it right because the value is a string. But once I input '08:30', firstly the excel will change the value in to a date type, and then node-xlsx will parse it into a  decimal type, now the value become 0.3541666666666667. I can't figure it out. I will appreciate it if someone can tell me how to deal with it. Thanks.

**Comment by cuspymd** [comment]
@RickonChen Hi.
Try `xlsx.parse('test.xlsx', {cellDates: true})`.
If it does not work, try this [change](https://github.com/cuspymd/node-xlsx/commit/e85ec010b3bf74239b2eb1c25fcd0561db1a7d52).
You should apply it to 'lib/index.js' not 'src/index.js' in your node-xlsx module.
This change will return always formatted strings of cells.
So you need to convert number strings to number type.

**Comment by ChristopheBougere** [comment]
Hi @mgcrea
Had the same issue and it seems to work for me also.
Do you plan to merge this commit on the trunk ? Or maybe add an option to let the user choose ?
Thanks

**Comment by RickonChen** [comment]
Hi @cuspymd ,
Noted. Thanks for you help.
