### ISSUE TITLE
I want to let the excel table content center, how to setting?

### ISSUE THREAD

**Issue by cjfff** [mgcrea/node-xlsx#80]

**Comment by cuspymd** [comment]
Currently, cell style does not work in [js-xlsx](https://github.com/SheetJS/js-xlsx). To give the cell a style, you need to change [js-xlsx](https://github.com/SheetJS/js-xlsx) to [xlsx-style](https://github.com/protobi/js-xlsx).
Please refer to [this change](https://github.com/cuspymd/node-xlsx/commit/8d753dacfe61178f41657599f55ac2674ff0e7b7).

**Comment by ccc865553742** [comment]
if i want to the table auto width and I should how to setting?

**Comment by ccc865553742** [comment]
thanks your reply~
