### ISSUE TITLE
Showing Date Formated Data As Numbers....

### ISSUE THREAD

**Issue by shivarajnaidu** [mgcrea/node-xlsx#82]
17/01/2017 this date value showing as 42752

**Comment by NextZeus** [comment]
+1

**Comment by ozknemoy** [comment]
same story 27.02.2013 --> 41332

**Comment by ozknemoy** [comment]
seem bad data and excel parse 41332 to 27.02.2013

**Comment by qrpike** [comment]
Having the same issue of dates turned into numbers. 2016-05-13 -> something like: 43010.791666666664

**Comment by jdesboeufs** [comment]
Just parse with `cellDates: true`
