### ISSUE TITLE
2018/7/9 00:15 excel type is Date but parsed to Number 43290.010416666664

### ISSUE THREAD

**Issue by NextZeus** [mgcrea/node-xlsx#85]

**Comment by liuzhen88** [comment]
I have same problem with your, are you solve it ?

**Comment by mind84** [comment]
Same for me

**Comment by ershaoyelxw** [comment]
Same for me..

**Comment by bogacg** [comment]
See : [solution in Issue 56](https://github.com/mgcrea/node-xlsx/issues/56#issuecomment-266064671)

Then simple `Date.parse()` for returned string date works.

**Comment by ccpwcn** [comment]
Same for me...

**Comment by chengroot** [comment]
Same for me......
