### ISSUE TITLE
Always wrong parsing of date on the third month

### ISSUE THREAD

**Issue by momegas** [mgcrea/node-xlsx#93]
When im trying to parse a date like 03/01/2018 i get the result 02/28/2018.

Also tried for next year and the problem persists.

Code i use for parsing:
```
export const getAttendancies = attendancesFileName => {
  const options = { cellDates: true };
  const workSheetsFromFile = xlsx.parse(`${attendancesFileName}`, options);
  const WorkSheetAttendances = workSheetsFromFile[0];
  return mapAttendances(WorkSheetAttendances.data.splice(1), employees);
};
```
I also noticed that when parsing a whole month i get this (moment parsed dates on the left raw value returned on the right):
![screenshot from 2018-06-20 11-13-30](https://user-images.githubusercontent.com/21096981/41645906-0b8354e8-747b-11e8-99cd-66f8692b21e9.png)

Notice that the 25th of the month is not displayed while it exists in my spread sheet

![screenshot from 2018-06-20 11-17-52](https://user-images.githubusercontent.com/21096981/41646116-a58f258a-747b-11e8-9262-8b0de7e2c6f7.png)

**Comment by anativ** [comment]
It parses the dates according to UTC time so if your are a UTC+X you will get a day before...
If your server will run on UTC time you won't have any problem
