### ISSUE TITLE
What's the benefit of using node-xlsx over js-xlsx ?

### ISSUE THREAD

**Issue by qiulang** [mgcrea/node-xlsx#94]
What's the benefit of using node-xlsx over js-xlsx ?

**Comment by mgcrea** [comment]
This project was created before `js-xlsx` and used to rely on a package from Microsoft with a non opensource friendly license.

When `js-xlsx` came around, this package was ported to `js-xlsx` to benefit from both a better maintained library and a friendlier license.

This package might provide a somewhat friendlier API is also maintained for retro-compatibility of old projects.

Except from that, you can totally skip this abstraction and work directly with `js-xlsx`.

**Comment by qiulang** [comment]
Thanks for clarification.
