### ISSUE TITLE
Error: Cannot find module './dist/cpexcel.js'

### ISSUE THREAD

**Issue by ccpwcn** [mgcrea/node-xlsx#97]
![_20180630100918](https://user-images.githubusercontent.com/5465756/42120454-b50ca6b6-7c4d-11e8-8ae2-dd3d5ec441e9.png)

Run on debugging mode, no errors
This error occurs when the production environment package that runs after opening with the electron-packager package the app.

**Comment by willgeek** [comment]
Hi,I have the same problem as you.
In the past two days, I have tried various ways that I can google, and I have not solved it. 
Finally, I switched to ejsxlsx, You can also try it.

https://github.com/sail-sail/ejsExcel

`/*
  use jsxlsx error: Uncaught error: cannot find module './dist/cpexcel.js' at
 use ejsexcel，it's perfect.
*/
const ejsexcel = require("ejsexcel");
const fs = require("fs");
const util = require("util");
var path = require('path');

const readFileAsync = util.promisify(fs.readFile);
const FileSaver = require('file-saver')

const downloadExcelFile = (async function(data, name, template) {
    template = path.join(__dirname, '../assets/files/template.xlsx');
	const exlBuf = await readFileAsync(template);
    const exlBuf2 = await ejsexcel.renderExcel(exlBuf, data);
    var target = path.join(__dirname, '../assets/files/'+name+'.xlsx');
    
    FileSaver.saveAs(
        new Blob([exlBuf2], {
            type: 'application/octet-stream',
        }),
        name+'.xlsx'
    );
    
});

module.exports = downloadExcelFile;`
